frontier_explorer:
  ros__parameters:
    map_topic: /map
    robot_pose_topic: /pf_pose_stamped
    goal_topic: /goal_pose
    occupied_threshold: 50
    min_frontier_cluster_size: 6
    min_goal_distance_m: 0.6
    goal_blacklist_radius_m: 0.6
    goal_publish_period_s: 2.0
    goal_timeout_s: 30.0
