frontier_explorer:
  ros__parameters:
    map_topic: /map
    pose_topic: /pf_pose_stamped
    goal_topic: /goal_pose
    occ_threshold: 50
    min_frontier_size: 6
    goal_min_distance: 0.6
    goal_blacklist_radius: 0.6
    publish_period_s: 2.0